name: example
description: Example app demonstrating remote_config_gen usage
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^5.1.3
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  remote_config_gen:
    path: ../

flutter:
  uses-material-design: true
