name: remote_config_gen
description: "A tool to generate type-safe remote config classes based on the Firebase Remote Config template"
version: 0.0.2
maintainer: Marcel Pinto (@marcelpinto)
homepage: https://shipflutter.com
repository: https://github.com/marcelpinto/remote_config_gen
issue_tracker: https://github.com/marcelpinto/remote_config_gen/issues

environment:
  sdk: ^3.7.2

dependencies:
  dart_style: ^3.1.0
  yaml: ^3.1.3
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2
